enum EzloginStatus {
  none,
  waitingForLogin,
  success,
  needAuthentication,
  newUser,
  alreadyCreated,
  wrongInfoWhileCreating,
  couldNotCreateUser,
  userNotFound,
  wrongUsername,
  wrongPassword,
  unrecognizedError,
  cancelled,
}
